export const ADD_TASK ='ADDTASK';
export const DELETE_FROM_RECYCLE_BIN='DELETE_FROM_RECYCLE_BIN';
export const DELETE_FROM_THE_TASKS='DELETE_FROM_THE_TASKS';
export const RECONSTRUCTION_TASK='RECONSTRUCTION_TASK';
export const ADD_TASK_TO_THE_RECYCLE_BIN='ADD_TASK_TO_THE_RECYCLE_BIN';